#This file stores configuration options for Iris, such as the currently active shaderpack
#Sun Sep 27 22:44:14 GMT-03:00 2026
allowUnknownShaders=false
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
enableShaders=true
maxShadowRenderDistance=32
shaderPack=ComplementaryReimagined_r5.9.3.zip
